name: docker-hub-push-frontend
on: 
  push:
    branches:
      - 'main'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with: 
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: rushikeshghodkedottech/contact-app-frontend:latest
          
  deploy:
    needs: build
    runs-on: self-hosted
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Pull latest image from Docker Hub
        run: docker pull rushikeshghodkedottech/contact-app-frontend:latest
        
      - name: Stop existing container
        run: docker stop contact-app-frontend || true
        
      - name: Remove existing container
        run: docker rm contact-app-frontend || true
        
      - name: Run new Docker container
        run: |
          docker run -p 80:80 \
          -e VITE_BASE_URL='http://34.241.159.181:3000/contacts' \
          --network three-tier \
          --name contact-app-frontend \
          rushikeshghodkedottech/contact-app-frontend
            
      - name: Clean up unused images
        run: docker image prune -f
